#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('🚀 Dojak API Server Setup');
  console.log('========================\n');

  // Check if .env already exists
  if (fs.existsSync('.env')) {
    const overwrite = await question('.env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('This setup will help you configure the Dojak API server.\n');

  // Get RPC configuration
  console.log('Dogecoin Core RPC Configuration:');
  console.log('(Make sure dogecoind is running with RPC enabled)\n');

  const rpcUser = await question('RPC Username [dogecoinrpc]: ') || 'dogecoinrpc';
  const rpcPass = await question('RPC Password (required): ');
  const rpcUrl = await question('RPC URL [http://localhost:33889]: ') || 'http://localhost:33889';
  const port = await question('API Server Port [3001]: ') || '3001';

  if (!rpcPass) {
    console.log('\n❌ RPC password is required!');
    rl.close();
    process.exit(1);
  }

  // Create .env file
  const envContent = `# Dojak API Server Configuration
# Generated by setup.js on ${new Date().toISOString()}

# Server Port
PORT=${port}

# Dogecoin Core RPC Configuration
DOGECOIN_RPC_URL=${rpcUrl}
DOGECOIN_RPC_USER=${rpcUser}
DOGECOIN_RPC_PASS=${rpcPass}

# Security
NODE_ENV=development

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=3
`;

  fs.writeFileSync('.env', envContent);

  console.log('\n✅ Configuration saved to .env');
  console.log('\nNext steps:');
  console.log('1. Make sure dogecoind is running with the RPC credentials above');
  console.log('2. Fund your faucet wallet with testnet DOGE');
  console.log('3. Run: npm run dev');
  console.log('4. Test: curl http://localhost:' + port + '/health');

  rl.close();
}

setup().catch(console.error);
