export {
  encodeDogenalsEra2AsciiModule,
  encodeDogenalsEra2Dxd,
  encodeDogenalsEra2Line,
  era2WirePrefixBytesDxdAscii,
  era2WirePrefixBytesDxdStylized,
  ERA2_DXD_WIRE_BYTE_THRESHOLD,
  ERA2_MARKER_UTF8,
  type DogenalsEra2ModuleKey,
} from './era2OpReturn';

export {
  DOGENALS_PROTOCOLS,
  findDogenalsProtocol,
  DSOCIAL_MARKER,
  DSOCIAL_KIND,
  DSOCIAL_REACTION,
  DSOCIAL_FLAG,
  encodeDsocialSignal,
  encodeDsocialSignalHex,
  encodeDsocialEngageLike,
  encodeDsocialFollow,
  encodeDsocialShortText,
  buildDsocialPostJson,
  parseDsocialSignal,
  DSOCIAL_MIN_LIKE_KOINU,
  planDsocialRevealPayments,
  DIGNAL_MARKER,
  DIGNAL_KIND,
  DIGNAL_FLAG,
  encodeDignalSignal,
  encodeDignalSignalHex,
  encodeDignalShortText,
  buildDignalMessageJson,
  DMP_MARKER,
  buildDmpEnvelope,
  buildDmpListEnvelope,
  stringifyDmpEnvelope,
  isDmpEnvelope,
  WOW_MARKER,
  buildWowSendJson,
  buildWowReactJson,
  DLOTTO_MARKER,
  isDlottoMarker,
  buildDlottoEnvelope,
} from '@dojak/core/dogenals';
export type {
  DogenalsProtocolEntry,
  DogenalsWalletRole,
  DsocialKind,
  DsocialReaction,
  EncodeDsocialSignalOpts,
  BuildDsocialPostOpts,
  DsocialRevealPayment,
  DsocialRevealPaymentKind,
  DignalKind,
  EncodeDignalSignalOpts,
  BuildDignalMessageOpts,
  DmpOp,
  DmpEnvelope,
  WowDestination,
  BuildWowSendOpts,
  DlottoOp,
} from '@dojak/core/dogenals';
